### ISSUE TITLE
browser support request. Firefox on android

### ISSUE THREAD

**Issue by Christophe31** [elky/django-flat-responsive#6]
Hi, as a Firefox enthusiast, I recommend and install it everywhere.
I test my websites mostly against it (with Firefox developer tools).
I think it already works ok with it but it would be cool to have "official" support.
(Even more since Mozilla contributed generously to django [[for those who forgot](https://www.djangoproject.com/weblog/2015/dec/11/django-awarded-moss-grant/), [mozilla contributions](http://www.django-rest-framework.org/topics/mozilla-grant/)]).

**Comment by elky** [comment]
Good point @Christophe31 

I just tested this app in Firefox (iOS and Android) and it works good. Unfortunately I can't install older FF versions for testing and Browserstack doesn't have mobile FF at all so I have to mention latest version of FF in readme file.

Thanks!
